version: "3.9"

services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "8000:8000"
      - "9000:9000"
      - "9443:9443"
    restart: unless-stopped
    volumes:
      - /pool-0/portainer/portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock

  registry:
    image: registry:latest
    ports:
      - 5000:5000
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/data
    restart: unless-stopped
    volumes:
      - /pool-0/portainer/registry-data:/data
