version: "3.9"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    network_mode: "host"
    ports:
      - "8000:8000"
      - "9000:9000"
    restart: unless-stopped
    volumes:
      - /var/lib/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
