version: "3.9"

services:
  portainer:
    image: portainer/portainer-ce:2.11.1-alpine
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - /var/lib/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
