version: "3.9"

services:
  portainer:
    image: portainer/portainer-ce:latest
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /pool-1/portainer-data:/data
