version: "3.9"

services:
  app:
    container_name: portainer
    image: portainer/portainer-ce:latest
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - /var/lib/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
