version: "3.9"

services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "8000:8000"
      - "9000:9000"
      - "9443:9443"
    restart: unless-stopped
    volumes:
      - /pool-1/portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
